<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>14</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NBuilder" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Core\Whisparr.Core.csproj" />
    <ProjectReference Include="..\NzbDrone.Test.Common\Whisparr.Test.Common.csproj" />
    <ProjectReference Include="..\Whisparr.Api.V3\Whisparr.Api.V3.csproj" />
    <ProjectReference Include="..\Whisparr.Http\Whisparr.Http.csproj" />
  </ItemGroup>
</Project>