<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Ical.Net" />
    <PackageReference Include="NLog" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Core\Whisparr.Core.csproj" />
    <ProjectReference Include="..\Whisparr.Http\Whisparr.Http.csproj" />
  </ItemGroup>
</Project>