<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <NoWarn>$(NoWarn);NU1507</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Dapper" Version="2.1.66" />
    <PackageVersion Include="Diacritical.Net" Version="1.0.4" />
    <PackageVersion Include="DryIoc.dll" Version="5.4.3" />
    <PackageVersion Include="DryIoc.Microsoft.DependencyInjection" Version="6.2.0" />
    <PackageVersion Include="FluentAssertions" Version="8.1.1" />
    <PackageVersion Include="FluentValidation" Version="11.11.0" />
    <PackageVersion Include="Ical.Net" Version="4.3.1" />
    <PackageVersion Include="ImpromptuInterface" Version="8.0.6" />
    <PackageVersion Include="Lib.Harmony" Version="2.3.5" />
    <PackageVersion Include="MailKit" Version="4.10.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="9.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Owin" Version="9.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.2" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageVersion Include="Mono.Posix.NETStandard" Version="5.20.1.34-servarr24" />
    <PackageVersion Include="MonoTorrent" Version="3.0.2" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="NBuilder" Version="6.1.0" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageVersion Include="NLog" Version="5.4.0" />
    <PackageVersion Include="NLog.Extensions.Logging" Version="5.4.0" />
    <PackageVersion Include="NLog.Targets.Syslog" Version="7.0.0" />
    <PackageVersion Include="Npgsql" Version="9.0.3" />
    <PackageVersion Include="NUnit" Version="4.3.2" />
    <PackageVersion Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageVersion Include="NunitXml.TestLogger" Version="3.0.131" />
    <PackageVersion Include="RestSharp" Version="112.1.0" />
    <PackageVersion Include="Selenium.Support" Version="4.29.0" />
    <PackageVersion Include="Selenium.WebDriver.ChromeDriver" Version="133.0.6943.14100" />
    <PackageVersion Include="Sentry" Version="5.2.0" />
    <PackageVersion Include="Servarr.FFMpegCore" Version="4.7.0-26" />
    <PackageVersion Include="Servarr.FFprobe" Version="5.1.4.112" />
    <PackageVersion Include="Servarr.FluentMigrator.Runner" Version="5.2.0.10" />
    <PackageVersion Include="Servarr.FluentMigrator.Runner.Postgres" Version="5.2.0.10" />
    <PackageVersion Include="Servarr.FluentMigrator.Runner.SQLite" Version="5.2.0.10" />
    <PackageVersion Include="SharpZipLib" Version="1.4.2" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.6" />
    <PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerGen" Version="7.3.1" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="9.0.2" />
    <PackageVersion Include="System.Data.SQLite.Core.Servarr" Version="1.0.115.5-18" />
    <PackageVersion Include="System.Resources.Extensions" Version="9.0.2" />
    <PackageVersion Include="System.Runtime.Loader" Version="4.3.0" />
    <PackageVersion Include="System.Security.Principal.Windows" Version="6.0.0-preview.5.21301.5" />
    <PackageVersion Include="System.ServiceProcess.ServiceController" Version="9.0.2" />
    <PackageVersion Include="System.Text.Encoding.CodePages" Version="9.0.2" />
    <PackageVersion Include="System.Text.Json" Version="9.0.2" />
  </ItemGroup>
</Project>