<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net9.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="RestSharp" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NzbDrone.Common\Whisparr.Common.csproj" />
    <ProjectReference Include="..\NzbDrone.Core\Whisparr.Core.csproj" />
  </ItemGroup>
</Project>